image: alpine/edge
packages:
  - nodejs
  - npm
  - curl
secrets:
  - f9b0470f-3ea4-4b49-aeb9-99e9f48d75e5
  - 9842a2f8-3365-4326-a3c0-9f155df7ae10

tasks:
  - configure-ssh: |
      mkdir -p ~/.ssh
      # echo "$f9b0470f-3ea4-4b49-aeb9-99e9f48d75e5" > ~/.ssh/id_ed25519
      # chmod 600 ~/.ssh/id_ed25519
      ssh-keyscan github.com >> ~/.ssh/known_hosts

  - mirror-to-github: |
      cd m1n.land
      git remote add github git@github.com:M1n-74316D65/m1n.land.git || true
      git push --mirror github

  - setup: |
      cd m1n.land
      npm ci

  - build: |
      cd m1n.land
      npm run build

  - deploy: |
      cd m1n.land
      # Install Vercel CLI
      npm install -g vercel
      
      # Deploy to Vercel using the provided token
      VERCEL_TOKEN="9842a2f8-3365-4326-a3c0-9f155df7ae10" vercel --prod --yes --token "$VERCEL_TOKEN"

