image: alpine/edge
packages:
  - nodejs
  - npm
  - curl
secrets:
  - f9b0470f-3ea4-4b49-aeb9-99e9f48d75e5
  - 9842a2f8-3365-4326-a3c0-9f155df7ae10
environment:
  VERCEL_TOKEN: 9842a2f8-3365-4326-a3c0-9f155df7ae10

tasks:
  - configure-ssh: |
      mkdir -p ~/.ssh
      # echo "$f9b0470f-3ea4-4b49-aeb9-99e9f48d75e5" > ~/.ssh/id_ed25519
      # chmod 600 ~/.ssh/id_ed25519
      ssh-keyscan github.com >> ~/.ssh/known_hosts

  - mirror-to-github: |
      cd m1n.land
      git remote add github git@github.com:M1n-74316D65/m1n.land.git || true
      git push --mirror github

  - deploy: |
      cd m1n.land
      curl -fsSL https://bun.sh/install | bash
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"
      bun install
      bun run build
      # Install Vercel CLI
      bun install -g vercel
      
      # Deploy to Vercel using the provided token
      vercel --prod --yes --token $VERCEL_TOKEN

